language: C++

before_install:
    - sudo apt-get install build-essential cppcheck git -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-5 g++-5 lcov -y
    - ./install_gtest.sh
    - ./install_libconfig.sh
    - gem install coveralls-lcov
    - sudo apt-get install python-sklearn python-numpy
    - sudo -H pip install yahoo_finance
    - gcc -v
    - g++ -v
    - gcov -v
    - lcov -v

script:
    - python model_gen/regression_analysis.py
    - make
    - bin/main models/test_model.mod
    - make clean
    - make TESTING=1
    - bin/main

after_failure:
    - g++ -o libconfig_test src/libcfg_test.cpp -lconfig++
    - ./libconfig_test

after_success:
    - cppcheck src/ --error-exitcode=1
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' 'googletest/*' --output-file coverage.info
    - lcov --list coverage.info
    - coveralls-lcov coverage.info
