language: C

before_install:
    - sudo apt-get install build-essential cppcheck git lcov -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -q
    - sudo apt-get install gcc-5 g++-5 -y
    - git clone https://github.com/google/googletest.git
    - cd googletest && cmake . && make && cd ..
    - gem install coveralls-lcov

script:
    - make TRAVIS=1
    - bin/main

after_success:
    - cppcheck src/ --error-exitcode=1
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' 'googletest/*' --output-file coverage.info
    - lcov --list coverage.info
    - coveralls-lcov coverage.info
